### ISSUE TITLE
Set up Continuous Delivery and artifactory

### ISSUE THREAD

**Issue by ViliusSutkus89** [ViliusSutkus89/pdf2htmlEX-Android#3]
Jitpack would be ideal one stop shop, but it limits build time to 15 minutes.
Try gitlab or github for CD and JFrog for artifactory.

**Comment by ViliusSutkus89** [comment]
Solved using GitHub Actions and Bintray jcenter

**Comment by TomTasche** [comment]
By the way, while being a little more complicated to consume the library, GitHub supports hosting packages too: https://proandroiddev.com/publishing-android-libraries-to-the-github-package-registry-part-1-7997be54ea5a

**Comment by ViliusSutkus89** [comment]
I've noticed that too, but haven't tried it out yet.
The downside I see is that you have to add something to main build.gradle. Android Studio already includes jcenter by default.
