### ISSUE TITLE
Annotations not shown

### ISSUE THREAD

**Issue by TomTasche** [ViliusSutkus89/pdf2htmlEX-Android#39]
As described in this issue, this library won't render annotations drawn on top of a PDF: https://github.com/opendocument-app/OpenDocument.droid/issues/219

There seems to be a setting for that, which is disabled by default: https://github.com/pdf2htmlEX/pdf2htmlEX/blob/7c9086b958e3da3ace34feb7306d7ed7e589bc9e/pdf2htmlEX/pdf2htmlEX.1.in#L138

**Comment by ViliusSutkus89** [comment]
We do have this available in the pdf2htmlEX C++ class ( https://github.com/ViliusSutkus89/pdf2htmlEX-Android/blob/89f509562497704e238f109e3b1ad5ab0afecfaa/dependency-builder/src/main/cpp/packages/pdf2htmlEX-Patch-Source-make-a-library.patch#L573 )

Will expose it in the Java interface

**Comment by ViliusSutkus89** [comment]
pdf2htmlEX-Android-v0.18.15 exposes `setProcessAnnotation` in Java interface.
https://github.com/ViliusSutkus89/pdf2htmlEX-Android/releases/tag/v0.18.15
