### ISSUE TITLE
Cannot convert protected PDF

### ISSUE THREAD

**Issue by AlenToma** [ViliusSutkus89/pdf2htmlEX-Android#74]
Hi trying now tha library and its working but somehow it cant convert some PDF.

I get ` ERROR  [Error: Document is copy protected!]` even though I can open it in the browser without any passwords.

is it something I am missing?

**Comment by ViliusSutkus89** [comment]
PDF has voluntary DRM copy protection feature. You can voluntarily ignore DRM by `pdf2htmlEX(...).setDRM(false)`
